# Site Settings
baseurl: ""

# Language of the website
lang: ko

# Search engine optimization settings
title: Donghyeon Kim's Resume and Portfolio Site
tagline: Powered By 'chrjabs/Grape-Academic-Theme'
description: Donghyeon Kim's Resume and Portfolio Site, Powered By 'jekyll' and 'chrjabs/Grape-Achademic-Theme'.
author: Donghyeon Kim (Bubble Kim)
twitter:
  username:
  card:
logo: /assets/img/smile.png
social:
  name: Donghyeon Kim (Bubble Kim)
  links:
    - https://github.com/BubbleK2m
    - https://www.linkedin.com/in/donghyeon-kim-40654a23a
locale: ko_KR

# Page Settings
theme_settings:
  title: Grape Academic Theme
  experience_title: EXPERIENCE
  interests_title: RESEARCH INTERESTS
  skills_title: SKILLS
  projects_title: PROJECTS
  presentations_title: PRESENTATIONS

# Build Settings
sass:
  sass_dir: _sass
  style: :compressed
plugins: ['jekyll-paginate', 'jekyll/scholar', 'jekyll-seo-tag']
bootstrap:
  assets: true

academicons:
  version: "1.9.1"
  integrity: "sha256-i1+4qU2G2860dGGIOJscdC30s9beBXjFfzjWLjBRsBg="
fontawesome:
  version: "5.15.4"
  integrity: "sha256-mUZM63G8m73Mcidfrv5E+Y61y7a12O5mW4ezU3bxqW4="
jquery:
  version: "3.6.0"
  integrity: "sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4="
